version: 2
parsers:
  yaml: frontmatter
path: "_entries/guestbook"
allowedFields:
  - name
  - message
  - date
requiredFields:
  - name
  - message
branch: "main"
commitMessage: "Neuer Gästebucheintrag von {{fields.name}}"
filename: "entry-{{timestamp}}.md"
moderation: false
