title: ZetsuNET
email: zetsuboushii@gmail.com
description: >-
baseurl: ""
url: ""
github_username: zetsuboushii
instagram_username: zetsuboushii
spotify_username: fefuqa5sxojouw2paqibdy5wi

collections:
  entries:
    output: true
    permalink: /:path/

# Build settings
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
